CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DIACHI VARCHAR(50),
	SODT VARCHAR(20)
)

CREATE TABLE LOAIPHONG
(
	MALP CHAR(5) PRIMARY KEY,
	TENLP VARCHAR(40),
	GIACOBAN MONEY
)

CREATE TABLE PHONG
(
	MAPHONG CHAR(5) PRIMARY KEY,
	MALP CHAR(5) REFERENCES LOAIPHONG(MALP), 
	GIAPHONG MONEY
)

CREATE TABLE DATPHONG
(
	MADAT CHAR(5) PRIMARY KEY,
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MAPHONG CHAR(5) REFERENCES PHONG(MAPHONG),
	NGDAT DATE,
	NGDEN DATE,
	NGDI DATE,
	SONGAYO INT
)

CREATE TABLE NHANVIEN
(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DIACHI VARCHAR(50),
	SODT VARCHAR(20),
	TENDN VARCHAR(30),
	MATKHAU VARCHAR(30)
)

CREATE TABLE DOAN
(
	MADOAN CHAR(5) PRIMARY KEY,
	TENDOAN VARCHAR(30),
	DOANCHAY INT,
	CALO REAL,
	GIADOAN MONEY
)

CREATE TABLE THUCUONG
(
	MATHUCUONG CHAR(5) PRIMARY KEY,
	TENTHUCUONG VARCHAR(30),
	KHONGDUONG INT,
	GIATHUCUONG MONEY
)

CREATE TABLE DICHVU
(
	MADV CHAR(5) PRIMARY KEY,
	TENDV VARCHAR(30),
	GIADV MONEY
)

CREATE TABLE DICHVUGD
(
	MADVGD CHAR(5) PRIMARY KEY,
	MADOAN CHAR(5) REFERENCES DOAN(MADOAN),
	MATHUCUONG CHAR(5) REFERENCES THUCUONG(MATHUCUONG),
	MADV CHAR(5) REFERENCES DICHVU(MADV)
)

CREATE TABLE THANHTOAN
(
	MATT CHAR(5) PRIMARY KEY,
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MANV CHAR(5) REFERENCES NHANVIEN(MANV),
	NGTT DATE,
	NOITT VARCHAR(30),
	THANHTIEN MONEY
)

CREATE TABLE GIAODICH
(
	MAGD CHAR(5) PRIMARY KEY,
	TENGD VARCHAR(30),
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MADAT CHAR(5) REFERENCES DATPHONG(MADAT),
	MANV CHAR(5) REFERENCES NHANVIEN(MANV),
	MATT CHAR(5) REFERENCES THANHTOAN(MATT),
	PHIDV MONEY
)


ALTER TABLE DATPHONG
ADD CONSTRAINT CHECK_NGAY CHECK (NGDEN<=NGDI)

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_TENDN CHECK (LEN(TENDN)<=30)

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_MATKHAU CHECK (LEN(MATKHAU)<=30)




