--TẠO CSDL QUẢN LÝ KHÁCH SẠN
CREATE DATABASE QUAN_LY_KHACH_SAN

USE QUAN_LY_KHACH_SAN

--BẢNG KHÁCH HÀNG
CREATE TABLE KHACHHANG
(
	MAKH CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DIACHI VARCHAR(50),
	SODT VARCHAR(20),
)

--BẢNG LOẠI PHÒNG
CREATE TABLE LOAIPHONG
(
	MALP CHAR(5) PRIMARY KEY,
	TENLP VARCHAR(40),
	GIACOBAN MONEY,
)

--BẢNG PHÒNG
CREATE TABLE PHONG
(
	MAPHONG CHAR(5) PRIMARY KEY,
	MALP CHAR(5) REFERENCES LOAIPHONG(MALP), 
	GIAPHONG MONEY,
)

--BẢNG ĐẶT PHÒNG
CREATE TABLE DATPHONG
(
	MADAT CHAR(5) PRIMARY KEY,
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MAPHONG CHAR(5) REFERENCES PHONG(MAPHONG),
	NGDAT SMALLDATETIME,
	NGDEN SMALLDATETIME,
	NGDI SMALLDATETIME,
	SONGAYO INT,
)

--BẢNG NHÂN VIÊN
CREATE TABLE NHANVIEN
(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN VARCHAR(40),
	DIACHI VARCHAR(50),
	SODT VARCHAR(20),
	TENDN VARCHAR(30),
	MATKHAU VARCHAR(30),
)

--BẢNG ĐỒ ĂN
CREATE TABLE DOAN
(
	MADOAN CHAR(5) PRIMARY KEY,
	TENDOAN VARCHAR(30),
	DOANCHAY INT,
	CALO REAL,
	GIADOAN MONEY,
)

--BẢNG THỨC UỐNG
CREATE TABLE THUCUONG
(
	MATHUCUONG CHAR(5) PRIMARY KEY,
	TENTHUCUONG VARCHAR(30),
	KHONGDUONG INT,
	GIATHUCUONG MONEY,
)

--BẢNG DỊCH VỤ
CREATE TABLE DICHVU
(
	MADV CHAR(5) PRIMARY KEY,
	TENDV VARCHAR(30),
	GIADV MONEY,
)

--BẢNG DỊCH VỤ GIAO DỊCH
CREATE TABLE DICHVUGD
(
	MADVGD CHAR(5) PRIMARY KEY,
	MADOAN CHAR(5) REFERENCES DOAN(MADOAN),
	MATHUCUONG CHAR(5) REFERENCES THUCUONG(MATHUCUONG),
	MADV CHAR(5) REFERENCES DICHVU(MADV),
)

--BẢNG THANH TOÁN
CREATE TABLE THANHTOAN
(
	MATT CHAR(5) PRIMARY KEY,
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MANV CHAR(5) REFERENCES NHANVIEN(MANV),
	NGTT SMALLDATETIME,
	NOITT VARCHAR(30),
	THANHTIEN MONEY,
)

--BẢNG GIAO DỊCH
CREATE TABLE GIAODICH
(
	MAGD CHAR(5) PRIMARY KEY,
	TENGD VARCHAR(30),
	MAKH CHAR(5) REFERENCES KHACHHANG(MAKH),
	MADAT CHAR(5) REFERENCES DATPHONG(MADAT),
	MANV CHAR(5) REFERENCES NHANVIEN(MANV),
	MATT CHAR(5) REFERENCES THANHTOAN(MATT),
	PHIDV MONEY,
)

------------------------MỘT SỐ RÀNG BUỘC TOÀN VẸN

-----Kiểm tra ngày đi(NGDI) của khách hàng sẽ lớn hơn hoặc bằng ngày đến(NGDEN) khi khách đặt phòng
ALTER TABLE DATPHONG
ADD CONSTRAINT CHECK_NGAY CHECK (NGDEN<=NGDI)

-----Tên đăng nhập và mật khẩu vào hệ thống quản lý của nhân viên chưa tối đa 30 ký tự
ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_TENDN CHECK (LEN(TENDN)<=30)

ALTER TABLE NHANVIEN
ADD CONSTRAINT CHECK_MATKHAU CHECK (LEN(MATKHAU)<=30)




